Comment vagrant tests for now

diff --git a/.github/workflows/tox.yml b/.github/workflows/tox.yml
--- a/.github/workflows/tox.yml
+++ b/.github/workflows/tox.yml
@@ -45,33 +45,33 @@ jobs:
       - name: Lint
         run: tox -e lint_all
 
-  vagrant_build:
-    needs: collect
-    runs-on: macos-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        scenario: ${{ fromJson(needs.collect.outputs.vagrant_scenarios) }}
-    steps:
-      - uses: actions/checkout@v2
-        with:
-          submodules: 'recursive'
-          path: ${{ env.checkout_path }}
-      - name: Update submodules to latest
-        run: |
-          cd "${{ env.checkout_path }}"
-          git submodule update --remote --recursive
-      - name: Set up Python
-        uses: actions/setup-python@v2
-      - name: Install dependencies
-        run: |
-          python -m pip install -U tox
-      - name: Run tox against ${{ matrix.scenario }}
-        run: |
-          set -ex
-          mv ansible_collections ~/work/
-          cd ~/work/${{ env.checkout_path }}
-          tox -e ${{ matrix.scenario }}
+          # vagrant_build:
+          #   needs: collect
+          #   runs-on: macos-latest
+          #   strategy:
+          #     fail-fast: false
+          #     matrix:
+          #       scenario: ${{ fromJson(needs.collect.outputs.vagrant_scenarios) }}
+          #   steps:
+          #     - uses: actions/checkout@v2
+          #       with:
+          #         submodules: 'recursive'
+          #         path: ${{ env.checkout_path }}
+          #     - name: Update submodules to latest
+          #       run: |
+          #         cd "${{ env.checkout_path }}"
+          #         git submodule update --remote --recursive
+          #     - name: Set up Python
+          #       uses: actions/setup-python@v2
+          #     - name: Install dependencies
+          #       run: |
+          #         python -m pip install -U tox
+          #     - name: Run tox against ${{ matrix.scenario }}
+          #       run: |
+          #         set -ex
+          #         mv ansible_collections ~/work/
+          #         cd ~/work/${{ env.checkout_path }}
+          #         tox -e ${{ matrix.scenario }}
 
   lint:
     runs-on: ubuntu-latest
@@ -133,7 +133,7 @@ jobs:
   release:
     needs:  # Only release if the build is good
       - build
-      - vagrant_build
+        #- vagrant_build
     if: github.event_name == 'release'
     runs-on: ubuntu-latest
     steps:
